### ISSUE TITLE
Select event 'date' of undefined

### ISSUE THREAD

**Issue by joristackaert** [edlynvillegas/evo-calendar#27] opened 2020-08-26 13:01 UTC
hey me again. 👋

Been fighting off this problem for a couple of hours now.

![image](https://user-images.githubusercontent.com/37837114/91304117-4452fc80-e7a9-11ea-8740-1662af83c7e1.png)

This is the result i get when clicking an event. the index is -1. i'm using your latest version of the code.  1.1.2

i'm filling an event ID from the database and this is a whole bunch of numbers (42481830)  in an array out of my asp.net controller -> encode to array in js. when i use id= "4hducye" for an event all seems to work fine, and  index = 0. But using whole bunch of numbers it fails. :/.

so when event id is numeric == fails   index = -1 and var modified_event = _.options.calendarEvents[index]; is undefined
when event id is Alfanumeriek == ok  index = 0 and var modified_event = _.options.calendarEvents[index]; is defined

so not really big issue because i can fix it by just adding a letter to the Id. :)

**Comment by edlynvillegas** [comment] 2020-08-27 07:18
Hello, I tried changing the event IDs into numbers (not strings), and it's working fine. :thinking: 

![image](https://user-images.githubusercontent.com/39414627/91409745-71221500-e878-11ea-97d9-d29a01f1217d.png)

![image](https://user-images.githubusercontent.com/39414627/91409701-5a7bbe00-e878-11ea-9154-bf9e7f266e42.png)

Or am I missing something? :sweat_smile:

**Comment by joristackaert** [comment] 2020-08-27 07:32
![image](https://user-images.githubusercontent.com/37837114/91410792-bda12c80-e847-11ea-8232-79884e2f0c5d.png)


well now i'm forcing it to have an id that otherwise would come from the Database. unless something weird happens when encoding my viewmodel to JS object.
Hmm I don't really have a clue :/. maybe it's only on my end.

**Comment by edlynvillegas** [comment] 2020-08-27 08:04
Hello @joristackaert, I get your problem now, I assigned an ID with numbers only but in string type, and I encountered your error. Check my latest commit :)

https://github.com/edlynvillegas/evo-calendar/blob/eec2e88a7026844c8dd06907304fd050cf7c35d8/evo-calendar/js/evo-calendar.js#L810-L820

The problem is, when the event's ID is like this **{ id: "1234" }**, in the DOM when it's assigned it looks like this **data-event-index="2313213"**. So when you get the event id in the element (_$(el).data('eventIndex')_), it became a number instead of string so the index would be **-1**

**Comment by joristackaert** [comment] 2020-08-27 10:37
Oww so that is the problem, I've been writing so much c# and typescript i forgot javascript sees that object as a number instead of a string.

thx 😉

if i have time on my hands i'll add some changes i've made to the evocalendar as pull requests.

**Comment by edlynvillegas** [comment] 2020-08-27 11:52
Sure, pull requests are welcome! Also, goodluck with your projects :slightly_smiling_face:

**Closed by edlynvillegas** 2020-08-27 11:52 UTC
